name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r Calculator/requirements.txt

      - name: Run tests
        run: pytest Calculator/Test/test_source_code.py
        working-directory: ${{ github.workspace }}

      - name: Build Docker image
        run: docker build -t advCalculator:latest .
        working-directory: Calculator
