name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r Calculator/requirements.txt

      - name: Set up PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:${{ github.workspace }}/Calculator" >> $GITHUB_ENV

      - name: Run tests
        run: pytest Test/test_source_code.py
        working-directory: Calculator

      - name: Build Docker image
        run: docker build -t ADVCalculator:latest .
        working-directory: Calculator
